services:
  - type: web
    name: bajaj-hackathon-be
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python --version
      pip install --upgrade pip==23.3.1
      pip install --upgrade setuptools==69.5.1 wheel==0.43.0
      pip install --only-binary=all --prefer-binary -r BE/requirements-render-safe.txt
    startCommand: |
      cd BE && python start_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: False
      - key: ENVIRONMENT
        value: production
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: 1
      - key: PIP_ONLY_BINARY
        value: ":all:"
    healthCheckPath: /health
