services:
  - type: web
    name: llm-query-retrieval
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
      - key: AUTH_TOKEN
    autoDeploy: false
