services:
  - type: web
    name: bajaj-hackathon-be
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: |
      cd BE && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: False
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
